[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@ethereum-attestation-service/eas-contracts/=lib/eas-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
